GITHUB_URL: https://github.com/softwaresaved/software-deposit-guidance
BASE_URL: https://softwaresaved.github.io/software-deposit-guidance
DISPLAY_URL: https://softwaresaved.github.io/software-deposit-guidance
# Uncomment this if creating PDFs:
# LINK_URL: https://softwaresaved.github.io/software-deposit-guidance
# Uncomment this if creating HTML for web site publication:
LINK_URL: .
VERSION: 1.0
GUIDANCE_DOI: 10.5281/zenodo.GuidanceDoi
GUIDANCE_PATH: SoftwareDepositGuidance.html
WHY_DOI: 10.5281/zenodo.WhyDoi
WHEN_DOI: 10.5281/zenodo.WhenDoi
WHERE_DOI: 10.5281/zenodo.WhereDoi
HOW_DOI: 10.5281/zenodo.HowDoi
WHAT_DOI: 10.5281/zenodo.WhatDoi
WHAT_NOT_DOI: 10.5281/zenodo.WhatNotDoi
DESCRIBE_DOI: 10.5281/zenodo.DescribeDoi
REVIEW_DOI: 10.5281/zenodo.ReviewDoi
LICENCE_DOI: 10.5281/zenodo.LicenceDoi
