VERSION: 1.0
GUIDANCE_DOI: 10.5281/zenodo.GuidanceDoi
GUIDANCE_URL: http://softwaresaved.github.io/software-deposit-guidance/GuidanceUrl
WHY_DOI: 10.5281/zenodo.WhyDoi
WHY_URL: http://softwaresaved.github.io/software-deposit-guidance/WhyUrl
WHEN_DOI: 10.5281/zenodo.WhenDoi
WHEN_URL: http://softwaresaved.github.io/software-deposit-guidance/WhenUrl
WHERE_DOI: 10.5281/zenodo.WhereDoi
WHERE_URL: http://softwaresaved.github.io/software-deposit-guidance/WhereUrl
HOW_DOI: 10.5281/zenodo.HowDoi
HOW_URL: http://softwaresaved.github.io/software-deposit-guidance/HowUrl
WHAT_DOI: 10.5281/zenodo.WhatDoi
WHAT_URL: http://softwaresaved.github.io/software-deposit-guidance/WhatUrl
WHAT_NOT_DOI: 10.5281/zenodo.WhatNotDoi
WHAT_NOT_URL: http://softwaresaved.github.io/software-deposit-guidance/WhatNotUrl
DESCRIBE_DOI: 10.5281/zenodo.DescribeDoi
DESCRIBE_URL: http://softwaresaved.github.io/software-deposit-guidance/DescribeUrl
REVIEW_DOI: 10.5281/zenodo.ReviewDoi
REVIEW_URL: http://softwaresaved.github.io/software-deposit-guidance/ReviewUrl
LICENCE_DOI: 10.5281/zenodo.LicenceDoi
LICENCE_URL: http://softwaresaved.github.io/software-deposit-guidance/LicenceUrl
