BASE_URL: %URL%
DISPLAY_URL: %URL%
# Uncomment this if building PDFs.
LINK_URL: %URL%
# Uncomment this if building HTML.
# LINK_URL: .
VERSION: %VERSION%
GUIDANCE_DOI: 10.5281/zenodo.GuidanceDoi
GUIDANCE_PATH: SoftwareDepositGuidance.html
WHY_DOI: 10.5281/zenodo.WhyDoi
WHY_PATH: WhyDepositSoftware.html
WHEN_DOI: 10.5281/zenodo.WhenDoi
WHEN_PATH: WhenToDepositSoftware.html
WHERE_DOI: 10.5281/zenodo.WhereDoi
WHERE_PATH: WhereToDepositSoftware.html
HOW_DOI: 10.5281/zenodo.HowDoi
HOW_PATH: HowToDepositSoftware.html
WHAT_DOI: 10.5281/zenodo.WhatDoi
WHAT_PATH: WhatToDeposit.html
WHAT_NOT_DOI: 10.5281/zenodo.WhatNotDoi
WHAT_NOT_PATH: WhatNotToDeposit.html
DESCRIBE_DOI: 10.5281/zenodo.DescribeDoi
DESCRIBE_PATH: HowToDescribeSoftwareDeposit.html
REVIEW_DOI: 10.5281/zenodo.ReviewDoi
REVIEW_PATH: HowToReviewSoftwareDeposit.html
LICENCE_DOI: 10.5281/zenodo.LicenceDoi
LICENCE_PATH: HowToChooseSoftwareLicence.html
