general:
    VERSION: 1.0
    URL_PREFIX: http://softwaresaved.github.io/software-deposit-guidance/
    DOI_PREFIX: doi:10.5281/zenodo.
    REF_TEMPLATE: Michael Jackson (ed.) (%s). Software Deposit: %s (Version %s). Zenodo. %s or visit %s.
guidance:
    what:
        title: What to deposit
        url: WhatUrl
        doi: WhatDoi
    how:
        title: How to deposit
        url: HowUrl
        doi: HowDoi
    what-not:
        title: What not to deposit
        url: WhatNotUrl
        doi: WhatNotDoi
    describe:
        title: How to describe a software deposit
        url: HowUrl
        doi: HowDoi
