GITHUB_URL: https://github.com/softwaresaved/software-deposit-guidance
BASE_URL: https://softwaresaved.github.io/software-deposit-guidance
DISPLAY_URL: https://softwaresaved.github.io/software-deposit-guidance
# Uncomment this if creating PDFs:
LINK_URL: https://softwaresaved.github.io/software-deposit-guidance
# # Uncomment this if creating HTML for web site publication:
LINK_URL: .
VERSION: 1.0
GUIDANCE_DOI: 10.5281/zenodo.1327310
WHY_DOI: 10.5281/zenodo.1327333
WHEN_DOI: 10.5281/zenodo.1327331
WHERE_DOI: 10.5281/zenodo.1327329
HOW_DOI: 10.5281/zenodo.1327327
WHAT_DOI: 10.5281/zenodo.1327325
WHAT_NOT_DOI: 10.5281/zenodo.1327323
DESCRIBE_DOI: 10.5281/zenodo.1327321
REVIEW_DOI: 10.5281/zenodo.1327314
LICENCE_DOI: 10.5281/zenodo.1327316
